# -*- coding: utf-8 -*-
"""Image_Caption_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKecXk3MfdN_52pta6CMRookp5zcQDzF
"""

!pip install streamlit transformers torch torchvision pillow --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model.py
# from transformers import BlipProcessor, BlipForConditionalGeneration
# from PIL import Image
# import torch
# 
# processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
# model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
# 
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model.to(device)
# 
# def generate_caption(image):
#     inputs = processor(images=image, return_tensors="pt").to(device)
# 
#     output = model.generate(
#         **inputs,
#         num_beams=7,          # better search
#         max_length=60,        # longer output
#         min_length=15,        # avoid short captions
#         repetition_penalty=1.2,
#         length_penalty=1.0,
#         early_stopping=True
#     )
# 
#     caption = processor.decode(output[0], skip_special_tokens=True)
# 
#     return caption
#

import streamlit as st
from PIL import Image
from model import generate_caption

st.set_page_config(page_title="Image Caption Generator", page_icon="🖼️")

st.title("🖼️ Image Caption Generator (BLIP Model)")
st.write("Upload an image or capture using your camera.")

# Upload option
uploaded_file = st.file_uploader(
    "Upload an Image",
    type=["jpg", "jpeg", "png"]
)

# Camera option
camera_image = st.camera_input("Or Take a Picture")

# Determine which image to use
image = None

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

elif camera_image is not None:
    image = Image.open(camera_image).convert("RGB")

# If we have an image
if image is not None:
    st.image(image, caption="Selected Image", width=500)

    if st.button("Generate Caption"):
        with st.spinner("Generating caption..."):
            caption = generate_caption(image)
        st.success("Caption: " + caption)

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!streamlit run app.py &>/dev/null &

!cloudflared tunnel --url http://localhost:8501